apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: akshaysriramoju/taskmanager:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/taskmanager
        - name: SPRING_DATASOURCE_USERNAME
          value: taskuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: taskpass
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
spec:
  selector:
    app: taskmanager
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
